Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 80

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120
